name: string_tokenizer_1
description: A package that splits Strings into multiple tokens.
version: 1.0.1
repository: https://github.com/Ahmad-Mtr/string_tokenizer
topics:
 - string
 - tokens
 - string-manipulation
environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
